version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"

  zookeeper:
    container_name: zookeeper
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"

  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    image: url-shortener
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - redis
      - zookeeper
