spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      username: root
      password: password
      database: urlshortener
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  zookeeper:
    base-url: "localhost:2181"
    counter-path: "/counters/url-counter"

application:
  base-url: "http://localhost:8080/"
  salt: "jeeneee"
